

<div class="container clearfix">
    <div class="title">
        <h2>Quản lý thư mục</h2>
    </div>
	
	<div class="inside_body" style="margin-top: 15px; float: left; width: 19%">
		<?php $this->element("category_tree"); ?>
	</div>
	
	<div style="float: left; width: 80%">
		<div id="treecontrol" style="display: block;">
			<a href="#" title="Collapse the entire tree below">Collapse All</a>
			<a href="#" title="Expand the entire tree below">Expand All</a>
		</div>
		
		
		<form method="POST" action="/categories/add">
			<fieldset>
				<legend>Khu vực tạo mới</legend>
				
					<div class="input text">
						<label for="CategoryName" class="lb">Tiêu đề: </label>
						<input name="title" type="text" maxlength="255" value="" id="title">
					</div>		
					
					<div class="input text">
						<label for="edit_text" class="lb">Mô tả: </label>
						<textarea name="description" id="description"></textarea>				
					</div>

					<div>
						<input type="hidden" name="parent_id" value="" id="parent_id">				
						<input type="radio" name="parent" id="Type0" value="0">
						<label for="Type0">Box lớn</label>
						<input type="radio" name="parent" id="Type1" value="1" checked="checked">
						<label for="Type1">Box con</label>	
					</div>
					
					<div>
						<input type="submit" name="btn_add" value="Hoàn thành">
					</div>
			</fieldset>
			<br />
		</form>

		<form method="POST" action="/categories/edit">
			<fieldset>
				<legend>Khu vực chỉnh sửa</legend>
					
					
					<div id="loading" style="display:none;" align="center">
						<div style="min-height: 30px; width: 100px; padding-top: 30px;">
							<img src="<?= STATIC_SERVER ?>/img/ajax-loader.gif" alt="">					
						</div>
					</div>
					
					<div id="form_edit" style="display:none;">
						<b>Chọn một option</b>
						<br>
						<div class="input text">
							<label for="position" class="lb">Di chuyển đến</label>
							<select name="position" id="position">
								<option value="-1">-- Không thay đổi --</option>
								<option value="0">Ra mục gốc</option>
								<?php 
									foreach ($this->categories as $key => $value) {
										echo "<option value='{$key}' >{$value}</option>";
									}
								?>
							</select>					
						</div>
						
						<div class="input text">
							<label for="CategoryName" class="lb">Sửa tiêu đề: </label>
							<input name="edit_name" type="text" maxlength="255" value="" id="edit_name">
						</div>		
						
						<div class="input text">
							<label for="edit_text" class="lb">Sửa mô tả: </label>
							<textarea name="edit_description" id="edit_description"></textarea>				
						</div>
						
						
						<input type="hidden" name="cid" value="" id="cid">			
						<input type="hidden" name="c_pos" value="" id="c_pos">
						<div>
							<span style="float: left" ><input type="submit" name="btn_edit" value="Hoàn thành"></span>
							<span style="float: right" ><input type="submit" name="btn_delete" onclick="return sub_delete();" value="Xóa mục này"> </span>
							<div style="clear: both;" > </div>
						</div>
					</div>
					
					
			</fieldset>
		</form>
			
		
	</div>
	<br style="clear: both;" /><br style="clear: both;" />
</div>

<script>

function select_field(obj) {
	var id 		= $(obj).attr('id');
	var name 	= $(obj).html();

	$("span").css('background',"white")
	$(obj).css('background',"#1BA9FF")
	$("#parent_id").val(id);
	
	$("#edit_name").val(name);
	$("#cid").val(id);
	//$("#position option[value='"+id+"']").attr('selected', 'selected');
	
	$("#loading").ajaxStart(function(){
		$('#form_edit').css('display','none');
		$(this).show();
	});
	$("#loading").ajaxStop(function(){
		$(this).hide();
		$('#form_edit').css('display','block');
	}); 
	
	$.ajax({
	   type: "POST",
	   url: '/categories/loadInfo/'+id,
	   success: function(msg){
			var val = msg.split(",--,");
			
			$("#cid").val(val[0]);
			$("#c_pos").val(val[1]);
			$("#edit_description").val(val[2]);
			$("#vip_action option[value='" + val[4] + "']").attr('selected', 'selected');
			$("#edit_glink").val(val[5]);
			$("#edit_m_title").val(val[6]);
			$("#edit_m_desc").val(val[7]);
			$("#edit_m_key").val(val[8]);
			
			if (val[3] == 1) $("#edit_type").attr("checked",true);
			else $("#edit_type").attr("checked",false);
		}
	});
	
	$.ajax({
	   type: "POST",
	   url: '/categories/loadList/'+id,
	   success: function(msg){
			$("#position").html(msg);
		}
	});
}

function sub_delete()	{
	
	if (confirm("Box này sẽ bị xóa, bạn có chắc chắn không ??")) {
		var id 		= $("#cid").val();
		location.href = '/categories/delete/'+id;
	}
	
	return false;
}
</script>