<div class="container clearfix">
    <div class="title">
        <h2>Refesh nội dung</h2>
    </div>

	<table border="1" width="500" cellpadding="10">
		<?php foreach ($this->categories as $c) { ?>
		
			<?php 
				if ($c->parent_id == 0) {
			?>
				<tr><th colspan="2" ><?=$c->name?></th></tr>
			<?php
				}
				else {
			?>
				<tr>
					<th><?=$c->name?></th>
					<td><a href="/topics/reload/<?=$c->cid?>"> Refesh </a></td>
				</tr>
		<?php } } ?>
	</table>
</div>

<?php $this->element("tiny_mce"); ?>