<div class="container clearfix">
    <div class="title">
        <h2>Tạo ảnh banner</h2>
    </div>

	<form method="POST" action="" enctype="multipart/form-data">
	<table border="1"  cellpadding="10">
		<tr>
			<th width="100">Tên banner</th>
			<td><input type="text" name="name" value="" /></td>
		</tr>
		<tr>
			<th width="100">URL đích</th>
			<td><input type="text" name="url" value="http://" /></td>
		</tr>
		<tr>
			<th>Ảnh banner</th>
			<td><input type="file" name="picture" ><label>Nên chọn ảnh có kích thước 960x265</label></td>
		</tr>
		<tr>
			<th> </th>
			<td><input type="submit" value="Hoàn thành" /></td>
		</tr>
	</table>
	</form>

</div>