<div class="container clearfix">
    <div class="title">
        <h2>Thay đổi ảnh banner</h2>
    </div>
	
	<form method="POST" action="" enctype="multipart/form-data">
	<table border="1"  cellpadding="10">
		<tr>
			<th width="100">Tên banner</th>
			<td><input type="text" name="name" value="<?=$this->banner->name ?>" /></td>
		</tr>
		<tr>
			<th width="100">URL đích</th>
			<td><input type="text" name="url" value="<?=$this->banner->url ?>" /></td>
		</tr>
		<tr>
			<th>Ảnh banner</th>
			<td>
			<img src='<?= STATIC_SERVER ?>/img/banners/<?="thumb_".$this->banner->filename; ?>' />
			<input type="file" name="picture" ><label>Nên chọn ảnh có kích thước 960x265</label>
			</td>
		</tr>
		<tr>
			<th>Trạng thái</th>
			<td><a href="/banners/change/<?=$this->banner->bid?>/<?=$this->banner->status?>"><?=$this->status[$this->banner->status] ?></a></td>
		</tr>
		<tr>
			<th><input type="hidden" name="old_file" value="<?=$this->banner->filename; ?>" /> </th>
			<td><input type="submit" value="Hoàn thành" /></td>
		</tr>
	</table>
	</form>

</div>