<div class="container clearfix">
    <div class="title">
        <h2>Quản lý banner ảnh</h2>
    </div>

	<a href="/banners/add" >Tạo banner mới</a>
	<br /><br />
	
	<table border="1">
		<tr>
			<th>Tên banner</td>
			<th>Ảnh banner</th>
			<th>Thao tác</th>
		</tr>
		
		<?php foreach($this->banners as $u) { ?>
		<tr>
				<td><?=$u->name?></td>
				<td><img src='<?= STATIC_SERVER ?>/img/banners/<?="thumb_".$u->filename; ?>' /></td>
				<td>
					<a href="/banners/change/<?=$u->bid?>/<?=$u->status?>"><?=$this->status[$u->status] ?></a> | 
					<a href="/banners/edit/<?=$u->bid?>">Sửa</a> | 
					<a href="/banners/delete/<?=$u->bid?>" onclick="return confirm('AreYouSure?');">Xóa</a>
				</td>
		</tr>
		<?php } ?>
		
	</table>
	
</div>