<div class="container clearfix">
    <div class="title">
        <h2>Tạo bài viết</h2>
    </div>

	<form method="POST" action=""  enctype="multipart/form-data">
	<table border="1" width="500" cellpadding="10">
		<tr>
			<th width="100">Category</th>
			<td>
				<select name="cid">
					<?php 
					foreach ($this->categories as $cate) {
					?>
							<option value="<?=$cate->cid?>" ><?=$cate->name?></option>
					<?php
					}
					?>
				</select>
			</td>
		</tr>
		<tr>
			<th>Tiêu đề</th>
			<td><input type="text" name="title" id="title" value="" /></td>
		</tr>
		<tr>
			<th>Ảnh đại diện</th>
			<td><input type="file" name="picture" ></td>
		</tr>
		<tr>
			<th>Nội dung</th>
			<td><textarea name="content" id="content" class="tinymce" value=""></textarea></td>
		</tr>
		<tr>
			<th>		</th>
			<td><input type="submit" value="Hoàn thành" /></td>
		</tr>
	</table>
	</form>

</div>

<?php $this->element("tiny_mce"); ?>