<div class="container clearfix">
    <div class="title">
        <h2>Quản lý bài viết</h2>
    </div>
	<p><a href="/topics/add" >Tạo bài viết</a></p>
	<br />
	<table border="1">
		<tr>
			<th>Category</th>
			<th>Tiêu đề</th>
			<th>Lượt đọc</th>
			<th>Vị trí hiển thị</th>
			<th>Thao tác</th>
		</tr>
		
		<?php foreach($this->topics as $t) { ?>
		<tr>
				<td><?=$this->list_cate[$t->category_id]?></td>
				<td><?=$t->title?></td>
				<td><?=$t->total_view?></td>
				<td><?=$t->position?></td>
				<td>
					<a href="/topics/edit/<?=$t->tid?>">Sửa</a> |
					<a href="/topics/delete/<?=$t->tid?>" onclick="return confirm('Bạn chắc chắn muốn xóa bài viết này??');">Delete</a>
				</td>
		</tr>
		<?php } ?>
		
	</table>
	
</div>