    <div class="span4">
            <div class="wrapRight"> 
                <!--Home ads-->
                <div class="homeAds borderRadius boxShadow"> <a href="#"><img src="/img/game02.jpg" alt="photo" /></a> </div>
                <div class="homeAds borderRadius boxShadow"> <a href="#"><img src="/img/game05.jpg" alt="photo" /></a> </div>
                <!--End Home ads--> 
            </div>
    </div>