 <h3 class="title01"><i class="icoBase icoSize02 icoSupport fl"></i>Hỗ trợ trực tuyến</h3>
                <div class="supportOnline borderRadius">
                    <ul class="supportOnline">
                        <li><a href="#"><i class="icoBase icoSize03 icoSkype"></i>
                            <p>Yahoo</p>
                            </a></li>
                        <li><a href="#"><i class="icoBase icoSize03 icoYahoo"></i>
                            <p>Skype</p>
                            </a></li>
                        <li><a href="#"><i class="icoBase icoSize03 icoEmail"></i>
                            <p>Email</p>
                            </a></li>
                    </ul>
                    <ul class="support borderRadius">
                        <li>Hoteline: <span>04 3715 4110</span></li>
                        <li><a href="#">Hỗ trợ kỹ thuật</a></li>
                        <li><a href="#">Hỗ trợ đối tác</a></li>
                    </ul>
                    <div style="text-align:center; margin:10px 0 0;">
                      <a target="_blank" href="http://tcoin.tamtay.vn/cashin/fpt"><img src="<?=HOME_URL?>/images/banners/fpt.jpg" alt="" /></a>
                      <a target="_blank" href="http://tcoin.tamtay.vn/cashin/vtc"><img src="<?=HOME_URL?>/images/banners/vtc.jpg" alt="" /></a>
                      <a target="_blank" href="http://tcoin.tamtay.vn/cashin#bank"><img src="<?=HOME_URL?>/images/banners/chuyen_khoan.png" alt="" /></a>  
                      <a target="_blank" href="http://tcoin.tamtay.vn/cashin/vdc"><img src="<?=HOME_URL?>/images/banners/NapT-CoinBangTheDiDong.png" alt="" /></a> 
                    </div>
                </div>