<!--------- BREADCRUMS ---------->
<?php 
	if (!empty($this->breadcrumb)) {
?>
		<ul class="breadcrumb">
			 <li><a href="/"><i class="icon-home"></i>Diễn đàn</a> <span class="divider">/</span></li>
<?php
		$i = 1;
		foreach ($this->breadcrumb as $bc) {
			$val = explode("|||",$bc);
			//if ($i == count($this->breadcrumb)) {
				// "<li class="active" ><?= $val[1]></a></li>";
?>
				
<?php
			//}
			//else {
?>
				<li ><a href="/frontpages/list/<?=$val[0]?>"><?= $val[1]?></a> <span class="divider">/</span></li>
<?php
			//}
			$title = $val[1];
			$parent = $val[2];
			$i++;
		}
?>
		</ul>
<?php
	}
?>

<!-------- END : BREADCRUMS ----------> 
<?php if ( !empty($parent) && !empty($this->cid) && ($this->obj != "create") ) { ?>
<div class="container" style="padding-bottom: 0; padding-top: 0;"">
<div class="topic-header clearfix">
	<h1><?=$title?></h1>
	
	<div class="pagination pagination-right">
		<?= $this->pager ?>
		<?php 
			if (!empty($this->user)) {
				if ($this->vip_action != 0 && $_SESSION['User']['group_id'] == MEMBER && $_SESSION['User']['is_vip'] != 1) {
					if ($this->vip_action == 1) {
						
					}
				}
				else {
				//if ( $_SESSION['User']['group_id'] != ADMIN && $_SESSION['User']['is_vip'] == 1 && ) {
		?>
				<span class="btn-create-topic"><a href="/frontpages/create?c=<?php echo $this->cid ?>" class="btn btn-log btn-signin"><i class="icon-quill"></i>Tạo bài viết</a></span>
		<?php } 
		} ?>
	</div>
</div>
</div>

<?php } ?>