<link rel="stylesheet" type="text/css" href="<?= STATIC_SERVER ?>/css/css.treeview.css"/>
<script type="text/javascript" src="<?= STATIC_SERVER ?>/js/jquery.treeview.js"></script>
<!-- 
	-	Javascript chay treeview jquery
	-->
<script>
$(document).ready(function(){
	$("#navigation").treeview({
		animated: "fast",
		control: "#treecontrol",
		collapsed: false,
		unique: false,
		persist: "location"
	});
});
</script> 

<style>
	span:hover {
		color: red;
		cursor: pointer;
	}
</style>


<!-- 
	-	PHP bien du lieu category thanh dang treeview
	-->
<ul id="navigation" class="treeview-red">
	<?php 
	
	$lists = $this->categories;
	
	$str = $old = "_";
	$i = $level = 0;
	$tag = '';
	
	foreach ($lists as $key => $list)	{
	
		if ( (strpos($list,'_') === false ) ) {
			if ($i != 0) {
				echo "</li>";
			}
			for ($j = 0; $j < $level; $j++) {
				echo str_replace("<","</",$tag);
			}
			echo '<li>';
			$str = $old = "_";
			$level = 0;
		}
		else 	{
			if ((strpos($list,$str) === false)) {
				if ($i != 0) {
					echo '</li>';
					
					if ( (strpos($list,$old) === false) ) {
						$num = 1;
						$num = ( strlen($old) - ( strlen(trim($list)) - strlen(trim(str_replace("_","",$list))) ) );

						for ($j = 0; $j < $num; $j++) {
							echo "</ul></li>";
							$level--;
							$str = $old;
							$old = substr($old, 1);
						}
						$tag = "<ul><li>";
						
					}
				}
				echo "<li>";
			}
			else {
				echo $tag = "<ul><li>";
				$level++;
				$old = $str;
				$str .= "_";
			}
		}
		echo "<span id='{$key}' onclick='select_field(this)'>".trim(str_replace("_","",$list))."</span>";
		
		$i++;
		if ($i == count($lists)) {
			for ($j = 0; $j < $level; $j++) {
				echo str_replace("<","</",$tag);
			}
		}
	
	} 
	
	?>
</ul>