<div class="helpboxleft">
<div class="accordion" id="accordion2">
	
	
	<?php 
	$paren_id = 0;
	$last_id 	= 0;
	$last_parent 	= 0;
	$script = ""; 
	$total = 0;
	foreach ($this->categories as $k => $li) {
	?>

	<?php
		if ($li->parent_id == 0) {
	?>	
			<div class="accordion-group">
				<div class="accordion-heading">
					<h4><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse<?=$li->cid?>"><?=$li->name?></a></h4>
				</div>
				<div id="collapse<?=$li->cid?>" class="accordion-body collapse in">
					<div class="accordion-inner">
						<ul>
	<?php
			$last_parent 	= 0;
			$last_id 			= 0;
			$paren_id = $li->cid;
		}
		else {
		?>
			<li><a <?=(!empty($this->cate->cid) && $this->cate->cid == $li->cid) ? ' class="selected"' : ""?> href="/<?=$li->cid?>-game-<?=rewrite_url($li->name)?>.html"><?=$li->name?></a></li>
	<?php
				$last_id = $li->cid;
		}
		
		if (empty($this->categories[$k+1]->parent_id)  ||  $this->categories[$k+1]->parent_id == 0 ) {
			echo "</ul></div></div></div>";
		}		
	}

	?>
	
</div>
</div>