<aside id="sidebar">
<div class="sidebar-block" id="popular-posts-widget">
    <div class="sidebar-title"><span>Popular posts</span></div>
  	<div class="pop-wg-wrap">
	    <ul class="side-popular-list" id="side-popular-list-0">
	    	<?php foreach ($this->tops as $k=>$t) { ?>
	     	<li class="sb-pop-row">
			    <div class="spr-lnk">
			      	<a href="/view/<?=$t->tid?>-<?=rewrite_url($t->title)?>.html" class="spr-number" data-num="<?=$k+1?>"></a>
			      	<a href="/view/<?=$t->tid?>-<?=rewrite_url($t->title)?>.html" class="spr-title"><?=$t->title?></a>
			    </div>
	   		</li>
	   		<?php } ?>
	  	</ul>
    </div><!-- pop-wg-wrap -->
  
</div>
</aside> 