<?php 
if (!empty($this->categories)) {
?>
<div class="rules">
	<fieldset>
		<legend><h3>Tools</h3></legend>
		<a href="/frontpages/delete/<?=$this->topic->tid?>/<?=$this->topic->category_id?>" onclick="if (!confirm('Bạn có thật sự muốn xóa bài viết này ?'))  return false; " >Xóa</a> | 
		<a href="/frontpages/hot/<?=$this->topic->tid?>/<?=$this->topic->hot?>" ><?php echo ($this->topic->hot == 1) ? "Bỏ đính" : "Đính lên đầu"; ?></a> 
		
		<br />
		<br />
		<form action="/frontpages/move" method="POST" >
			<b>Move to: </b>
			<select name="cid">
				<?php 
				$i =0;
				foreach ($this->categories as $cate) {
					if ($cate->parent_id == 0) {
						if ($i > 0) {
							echo "</optgroup>";
						}
						
						echo "<optgroup label='$cate->name'>";
						$i++;
					}
					else {
						$selected = ($cate->cid == $this->topic->category_id) ? "selected='selected'" : "";
				?>
						<option value="<?=$cate->cid?>" <?=$selected?>><?=$cate->name?></option>
				<?php
					}
				}
				?>
			</select>
			
			<input type="hidden" name="topic_id" value="<?=$this->topic->tid?>" />
			<input type="submit" value="GO" />
		</form>
	</fieldset>
<br/>
</div>
<?php } ?>