<?php require_once(APP_PATH . 'helpers/convert.php');    ?>
<div id="content-wrap" style="visibility: visible; opacity: 1;">
	<div id="content" style="visibility: visible; opacity: 1; ">
		<div id="face">
			<?php if (!empty($this->topics)) { ?>
			<section id="articles">
				<?php foreach ($this->topics as $t) { ?>
				<div data-title="Our favorite tweets of the week: February 23, 2015 – March 1, 2015" id="post-74118" class="chess-item parallax">
					<div class="mcipa-wrap">
						<?php 
						$filename = "";
						if (!empty($t->image)) {
							$filename = STATIC_SERVER . "/img/banners/" . $t->image;
						}
						?>
						<a href="https://medium.com/backchannel/getting-into-tech-if-you-re-not-an-obvious-fit-2dd9283f4b09?source=top-stories" data-action="open-post" data-action-value="/backchannel/getting-into-tech-if-you-re-not-an-obvious-fit-2dd9283f4b09?source=top-stories" class="block-image" style="background-size: cover;background-image:url('<?=$filename?>')"></a>

						<div class="mci-post-area">  
						   	<div class="mc-title-area">
						     
						      	<a class="home-cat-lnk" href="/category/<?=$t->category_id?>-<?=rewrite_url($this->cates[$t->category_id])?>" data-cat="Social Media">
						      		<?=$this->cates[$t->category_id]?></a>
						     	<h2 class="post-title">
						        	<a class="single-ajax-lnk" href="/view/<?=$t->tid?>-<?=rewrite_url($t->title)?>.html"><?=$t->title?></a>
						     	</h2>
						     
						   	</div>
						   
						   
							<div class="mc-item-excerpt"><?=word_limiter(strip_tags($t->content),50)?></div>  
						</div>
					</div>
				</div>
				<?php } ?>
			</section>
			<?php } else {
				echo "<br /><br /><br /><p>Request failure, no matches found.</p>";
			} ?>
		</div>

		<?php 
		if (!empty($this->pager)) {
			echo $this->pager;
		}
		?>
</div> <!-- content-wrap -->
  
</div>
<?=$this->element("rights")?>


<?php if (!empty($this->topics)) { ?>

<?php 
if (!empty($this->page)) {
	$url = explode("?",$this->currentURL);
	$currentURL = $url[0];
?>
<ul class="pager">
	<?php if($this->page >1) { ?>
	<li class="previous"> <a href="<?=$currentURL?>?page=<?=$this->page-1?>" class="">&larr; Previous</a> </li>
	<?php } ?>
	<?php if (count($this->topics)>9) { ?>
	<li class="next"> <a href="<?=$currentURL?>?page=<?=$this->page+1?>" class="">Next &rarr;</a> </li>
	<?php } ?>
</ul>
<?php } } ?>