<div class="container clearfix">
    <div class="title">
        <h2>Add new account</h2>
    </div>

	<form method="POST" action="" >
	<table border="1" width="500" cellpadding="10">
		<tr>
			<th width="100">Username</th>
			<td><input type="text" name="username" class="text" /></td>
		</tr>
		<tr>
			<th>New password</th>
			<td><input type="password" name="new_password" class="text" /></td>
		</tr>
		<tr>
			<th>Confirm password</th>
			<td><input type="password" name="cf_password" class="text" /></td>
		</tr>
        <tr>
            <th>MD username</th>
            <td><input type="text" name="md_name" class="text" /></td>
        </tr>
        <tr>
            <th>MD ID</th>
            <td><input type="text" name="md_id" class="text" /></td>
        </tr>
        <tr>
            <th>MD API key</th>
            <td><input type="text" name="md_key" class="text" /></td>
        </tr>
		<tr>
			<th>
			</th>
			<td><input type="submit" value="Create" /></td>
		</tr>
	</table>
	</form>

</div>