<div class="container clearfix">
    <div class="title">
        <h2>Edit account</h2>
    </div>

	<form method="POST" action="" >
	<table border="1" width="500" cellpadding="10">
		<tr>
			<th width="100">Username</th>
			<td><?=$this->user->username?></td>
		</tr>
		<tr>
			<th>New password</th>
			<td><input type="password" name="new_password" class="text" /></td>
		</tr>
		<tr>
			<th>Confirm password</th>
			<td><input type="password" name="cf_password" class="text" /></td>
		</tr>
		<tr>
			<th>
				<input type="hidden" name="uid" value="<?=$this->user->uid?>" />
			</th>
			<td><input type="submit" value="Update" /></td>
		</tr>
	</table>
	</form>

</div>