<div class="container clearfix">
    <div class="title">
        <h2>Quản lý tài khoản</h2>
    </div>
	<p><a href="/users/add" >Add new account</a></p>
	<br />
	<table border="1">
		<tr>
			<th>uid</td>
			<th>Username</th>
			<th>Action</th>
		</tr>
		
		<?php foreach($this->users as $u) { ?>
		<tr>
				<td><?=$u->uid?></td>
				<td><?=$u->username?></td>
				<td>
					<a href="/users/edit/<?=$u->uid?>">Edit</a> |
					<?php if($_SESSION['User']->uid != $u->uid) { ?>
					<a href="/users/delete/<?=$u->uid?>" onclick="return confirm('Are you sure');">Delete></a> |
					<a href="/users/block/<?=$u->uid?>/<?=$u->status?>"><?=($u->status == 1) ? "Active" : "Deactive" ?></a>
					<?php } ?>
				</td>
		</tr>
		<?php } ?>
		
	</table>
	
</div>