<!DOCTYPE html>
<!-- saved from url=(0032)http://www.webdesignerdepot.com/ -->
<html class="wf-lftetica-i7-active wf-lftetica-i8-active wf-lftetica-n7-active wf-lftetica-n8-active wf-proximanovasoft-n4-active wf-proximanovasoft-n7-active wf-active">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title><?=(!empty($this->h_title)) ? $this->h_title . " | " : ""; ?>Mining Dutch Statistic</title>
		<link rel="stylesheet" type="text/css" href="/css/alphaart.css" media="screen, print">


		<!-- All in One SEO Pack 2.2.3.1 by Michael Torbert of Semper Fi Web Design[113,148] -->
		<meta name="description" content="Web Design Resources for Web Designers. We include Photoshop Tutorials, WordPress Plugins, and Web Development tools. Download free icons, Photoshop brushes and">

		<meta name="keywords" content="web design, web designer, photoshop, graphic design, css, illustrator, twitter, photography, free icons, wordpress, web developer, web development">
		<!-- /all in one seo pack -->
 
  
    
		<style type="text/css">.tk-proxima-nova-soft,body{font-family:"proxima-nova-soft",sans-serif;}#main-menu a,#search-field,#shrs-counter,.ap-title,.asection-title,.button,.cp-title,.entry-content blockquote,.footer-submit-btn,.form-label,.hc-parent-lnk,.home-cat-lnk,.sidebar-title,.single-meta,.sm-cat-links,.spr-lnk,.tk-lft-etica,.widget-poll .poll-wh-style,h1,h2{font-family:"lft-etica",sans-serif;}</style>



<body class="home blog  posts-body home-body">
	<?=$this->element("menu_main")?>
  


<div id="main-wrap" style="visibility: visible; opacity: 1;">
  
  	<div class="content-block" id="mw-block" style="visibility: visible; opacity: 1;">

       <?=$this->content?>
  		 
	</div><!-- main-wrap -->

<footer id="footer-wrap">
 
  	<div class="long-art"></div>
  	<div id="footer-nav" class="content-block">
      <div class="footer-left">

     
      
      <div id="footer-copyright">
      	©2018 All Rights Reserved
     </div>
     
     </div>
     
    
    <div id="footer-social-icons">

	    <span class="fsl-item">
	     	<a class="header-social-lnk fsl-fb" target="_blank" href="#">
	       		<span class="header-social-icon icon-facebook"></span>
	      	</a>
	    </span> 
	</div>   
     
  	</div>
</footer>




</body></html>