<!DOCTYPE html>
<html class="screen-scroll wf-freighttextpro-i4-active wf-freighttextpro-i7-active wf-freighttextpro-n4-active wf-freighttextpro-n7-active wf-jafberninosans-n3-active wf-jafberninosans-n4-active wf-jafberninosans-n6-active wf-jafberninosans-n7-active wf-active">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" user-scalable="no">
<title><?=(!empty($this->h_title)) ? $this->h_title . " | " : ""; ?>He's Man</title>




<link rel="stylesheet" href="/css/style.css">
<!--[if lt IE 9]>
<script charset="UTF-8" src="//dnqgz544uhbo8.cloudfront.net/_/fp/js/shiv.RI2ePTZ5gFmMgLzG5bEVAA.js">
</script><![endif]-->

<style type="text/css">.tk-freight-text-pro{font-family:"freight-text-pro",sans-serif;}.tk-jaf-bernino-sans{font-family:"jaf-bernino-sans",sans-serif;}
</style>


<meta property="og:description" content="He's Man">
<meta property="og:type" content="website">
</head>

<body itemscope="" itemtype="http://schema.org/Article" class=" browser-chrome os-mac js-loaded" data-action-scope="_actionscope_0">

<div class="site-nav-overlay">
</div>

<div class="container" id="container">

<div class="butter-bar error" data-action-scope="_actionscope_1">
</div>

<div id="_obv.shell._surface_1392605806032" class="surface" style="visibility: visible; display: block;">

<div class="screen-content" data-action-scope="_actionscope_2" data-scroll="native">

<div class="image-home-header-bleed" data-scroll="blur-cover">

<div class="image-src picker-target" style="background-image: url('/img/man.jpg') ">
</div>


</div>

<div class="layout-foreground scrolling-region" tabindex="-1">


<header class="hero hero-home layout-single-column">

<div class="align-middle layout-single-column layout-foreground layout-fill-height">

<div class="align-block"><h1 class="hero-title">He's man</h1>

<p class="hero-description hero-description-tagline">The happiness of man.</p>

<!-- <div class="hero-actions btn-set"><a class="btn btn-light btn-small" href="https://medium.com/about/9e53ca408c48" title="Learn more about Medium"> -Learn more</a> 
</div>
-->
</div>
</div></header>

<nav class="nav-tabs nav-tabs-light  layout-single-column">
	<ul class="nav-tabs-list">
		<li class="nav-tabs-item <?=(empty($this->cid) || $this->cid == 0) ? 'active' : '' ?>"><a class="nav-tabs-anchor" href="/">Home</a></li>
		<li class="nav-tabs-item <?=($this->cid == 1) ? 'active' : '' ?>"><a class="nav-tabs-anchor" href="/articles">Articles</a></li>
		<li class="nav-tabs-item <?=($this->cid == 2) ? 'active' : '' ?>"><a class="nav-tabs-anchor" href="/blog">Blog</a></li>
	</ul>
</nav>

<div class="background-white">
	<div class="bucket layout-single-column ">
		<?=$this->content?>
	</div>

	<footer class="footer btn-set layout-single-column " style="color: #b3b3b1;font-size: 12px;">
		©2014 <a class="btn btn-link" href="http://hesman.net" >He's man</a>. All rights reserved.
	</footer>
</div>


</div>
</div>
</div>
</div>


<div class="loading-bar">
</div>



</body>
</html>