<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<title><?=(empty($this->cate->m_title) ? "Chơi game Chắn Online | đánh Chắn Online | ".THAPTHANH_COOKIE_DOMAIN : $this->cate->m_title) ?></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="google-site-verification" content="58v91UIUqbPGHL5VFTVI2xq_Z_HmdzJOi0m82noMcgk" />
<meta name="description" content="<?=(empty($this->cate->m_desc) ? "Chơi game Chắn Online, đánh Chắn Online, chắn online, game online, đánh bài, bài lá, tổ tôm, chơi chắn, đánh chắn, thapthanh.com cổng trò chơi trực tuyến hàng đầu tại Việt Nam" : $this->cate->m_desc) ?>" />
<meta name="keywords" content="<?=(empty($this->cate->m_key) ? "Chơi game Chắn Online, đánh Chắn Online, chắn online, game online, đánh bài, bài lá, tổ tôm, chơi chắn, đánh chắn, thapthanh.com cổng trò chơi trực tuyến hàng đầu tại Việt Nam" : $this->cate->m_key) ?>" />    

<link rel="stylesheet" type="text/css" href="<?= STATIC_SERVER ?>/template/muoi/css/bootstrap.css" />
<link rel="stylesheet" type="text/css" href="<?= STATIC_SERVER ?>/template/muoi/css/site.css" />
<link rel="stylesheet" type="text/css" href="<?= STATIC_SERVER ?>/css/content.css" />

<script type="text/javascript" src="<?= STATIC_SERVER ?>/template/muoi/js/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="<?= STATIC_SERVER ?>/template/muoi/js/appsScript.js"></script>
<script type="text/javascript" src="<?= STATIC_SERVER ?>/template/muoi/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?= STATIC_SERVER ?>/js/thapthanh.js" ></script>

</head>
<body>


<!--End: NAV--> 
<style>
 nav {height:61px;}
 .bgNoel {height:524px !important; position:absolute !important; left:0; right:0;
 margin: 0 auto 0;
 padding: 0 0 10px;
 background: url('<?= STATIC_SERVER ?>/template/muoi/images/navBgCenter-1.png') top center no-repeat;
 }
</style>
<!--START: NOEL-->

<div class="wrapAll">
<!--Start: HEADER-->
	<header>
	    <div >
    	<div class="container">
			<h1 id="logo" class="pull-left">
				<a href="<?= $this->url(THAPTHANH_COOKIE_DOMAIN) ?>" class="logo" title="Trang chủ <?=THAPTHANH_COOKIE_DOMAIN?>">
					<img src="<?=$this->url(THAPTHANH_STATIC_SERVER)?>/assets/muoi/images/logo.png" alt="Trang chủ <?=THAPTHANH_COOKIE_DOMAIN?>">
				</a>
			</h1>
			<div class="btn-menuRes pull-right"><a href="#"></a></div>
			<div class="clearfix menuResponsive">
				<ul class="menuHeader pull-left">
					<li id="m_home"><span><a href="<?=$this->url(THAPTHANH_URL)?>">Trang chủ</a></span></li>
					<li id="m_game" class="game"><span><a href="#">Game</a></span>
						<div class="menuGame">
							<ul class="clearfix">
								<?php $i=1; foreach ($this->list_apps as $app) { ?>
									<li class="game<?=$i?>"><a href="<?=$this->url(APPS_URL)?>/<?=$app->alias?>"><span class="avatarG"><img src="<?=$this->url(THAPTHANH_STATIC_SERVER)?>/images/games/<?=$app->alias?>.png" alt="<?=$app->title?>" title="<?=$app->title?>" style="width:115px;height: 83px;"></span><span>Chơi ngay</span></a></li>
								<?php $i++; } ?>
							</ul>
						</div>
					</li>
					<li id="m_news"><span><a href="<?=$this->url(THAPTHANH_URL)?>/news/cat">Tin tức</a></span></li>
					<li id="m_profile"><span><a href="<?=$this->url(THAPTHANH_URL)?>/home/<?=@$this->user->username?>">Nhà tôi</a></span></li>
					<li id="m_group"><span><a  rel="nofollow" href="<?=$this->url(GROUP_URL)?>">Nhóm</a></span></li>
					<li id="m_bank"><span><a  rel="nofollow" href="<?=$this->url('tcoin.'.THAPTHANH_COOKIE_DOMAIN)?>">Ngân hàng</a></span></li>
					<li id="m_forum"><span><a href="<?=$this->url('forum.thapthanh.com')?>">Diễn đàn</a></span></li>
					<li id="m_support" class="selected"><span><a  rel="nofollow" href="<?=$this->url(THAPTHANH_SUPPORT)?>">Hỗ trợ</a></span></li>
				</ul>
			
				<!-- Start Login - Register OR Noti -->
				<ul class="user pull-right signout">
					<?php if (!empty($this->user) && $this->user->uid > 0 ) { ?>
					<!--<li>
						<a href="#">
							<span class="notification">
								<i class="ico-bell ico01"></i>
								<span class="number">5</span>
							</span>
						</a>
					</li>-->
					<li class="userava">
						<a href="#"><img class="img-circle" style="background:url('<?=IMG_SERVER.'/'.$this->user->uid.'.ava?'.time()?>') center center no-repeat; background-size:cover"><?=$this->user->username?><i class="caret"></i></a>
						<div class="usersetting">
								
							<ul>
								<li><a href="/nhom-cua-toi.html">Nhóm của tôi</a></li>
								<li><a href="<?=$this->url(IDS_URL)?>/password/change">Đổi mật khẩu</a></li>
								<li><a href="<?=$this->url(IDS_URL)?>/avatar">Đổi avatar</a></li>
								<li><a href="<?=$this->url(IDS_URL)?>/secure/info">Thông tin cơ bản</a></li>
								<li><a href="<?=$this->url(IDS_URL)?>/secure/verify">Xác nhận tài khoản</a></li>
								<!--<li><a href="B-mxh-tt-nhatoi-message.html">Tin nhắn</a></li>-->
								<!-- <li><a href="/ban-be.html">Bạn bè</a></li> -->
								<li><a href="<?=$this->url(IDS_URL)?>/users/logout">Thoát</a></li>
							</ul>
							 
						</div>
					</li>
					<?php } else { ?>
					
					<li class="signinup"><a  rel="nofollow" href="<?=$this->url(IDS_URL)?>/users/register?ref=<?=urlencode($this->curPageURL())?>"><span><i class="ico-signup ico01"></i></span><b>Đăng ký</b></a></li>
					<li class="signinup"><a  rel="nofollow" href="<?=$this->url(IDS_URL)?>/users/login?ref=<?=urlencode($this->curPageURL())?>"><span><i class="ico-signin ico01"></i></span><b>Đăng nhập</b></a></li>

					<?php } ?>
				</ul>
				<!-- END LOGIN - REGISTER -->
			</div>
		</div>
        </div>
	</header>
	<div class="clearfix"></div>
<!--End: HEADER-->
<!--Start: NAV-->
	<nav>
		<div class="topNav">
		</div>
	</nav>
	<div class="clearfix"></div>
<!--End: NAV-->
<!--Start: CONTENT-->
<div class="mainContent contentResponsive">
		<div class="wrap clearfix">
			<!--Start: WRAP RIGHT-->
			<div class="wrap-news wrap-signin">
				<div class="page-content01 clearfix">
					<h2>Hỗ trợ</h2>
					<?=$this->content?>
				
					<?php if (!empty($this->list_apps)) { ?>
					<div class="clearfix"></div>
					<div class="boxleftResponsive otherGame">
						<h3>Game bài khác</h3>
						<div class="itemGame"> 
							<ul>
								<li>
									<a href="<?=$this->url("tank.thapthanh.com")?>" class="logo"><img style="width: 150px;height: 100px;" src="<?=$this->url(THAPTHANH_STATIC_SERVER)?>/images/games/tank.png" alt="TANK TANK" title="TANK TANK" /></a>
									<a href="<?=$this->url("tank.thapthanh.com")?>" class="btn btn-danger btn-orange">Chơi ngay</a>
									<a href="<?=$this->url("http://tank.thapthanh.com/news/view/40/Huong-dan-Tao-Tai-Khoan.html")?>" class="btn btn-danger btn-grey" target="_blank">Hướng dẫn</a>
								</li>
								<?php foreach ($this->list_apps as $app) {
									$play_url = (!empty($is_mob) && $is_mob == 1) ? "http://m.thapthanh.com": APPS_URL."/".$app->alias;
								?>
								<li>
									<a href="<?=$this->url(APPS_URL)?>/<?=$app->alias?>" class="logo"><img src="<?=$this->url(THAPTHANH_STATIC_SERVER)?>/images/games/<?=$app->alias?>.png" alt="<?=$app->title?>" title="<?=$app->title?>" /></a>
									<a href="<?=$this->url($play_url)?>" class="btn btn-danger btn-orange">Chơi ngay</a>
									<a href="<?=$this->url($app->tutorial_url)?>" class="btn btn-danger btn-grey">Hướng dẫn</a>
								</li>
								<?php } ?>
							</ul>
						  
						</div>
					</div>
					<?php } ?>
				</div>
			</div>
			<!--End: WRAP NEWS--> 
		</div>
</div>
<!--End: CONTENT-->
<div class="clearfix"></div>

</div>
<!--Start: Footer-->
<footer>
	<!--Start: Footer-->
	<div class="footer clearfix">
		<div class="wrapfooter"> <span><i class="ico05 ico-telephone"></i>Hỗ trợ 1: 0969202634</span> <span><i class="ico05 ico-telephone"></i>Hotline: 0982422740 - 0934578105 (18h - 24h và ngày lễ)</span> <span><i class="ico05 ico-email"></i><a rel="nofollow" href="mailto:hotro@thapthanh.com">hotro@thapthanh.com</a></span> </div>
		<span class="btn-helpft"><i class="ico05 ico-telephone"></i></span>
		<div class="footer-func">
		</div>
	</div>
	<!--End: Footer--> 
	<?//$footer?>
</footer>
<!--End: Footer-->

<?=(!empty($this->cate->glink) ? '<div style="position: fixed; z-index:-9999999;">'.$this->cate->glink.'</div>' : "") ?>

<?php if (  (!empty($_GET['do']) && $_GET['do'] == 'login') ) { 
	if (empty($this->user) || $this->user->uid <= 0) {
?>
<!--START : MODAL-->
<div class="modal in">
  <div class="modal-header" style="padding:0;">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true" style="margin:8px 8px 0 0">×</button>
    <ul class="nav nav-tabs" style="margin:0; border-bottom:none">
		<li class="active"><a href="#login" data-toggle="tab">Đăng nhập</a></li>
		<li><a href="#signup" data-toggle="tab">Đăng ký</a></li>
    </ul>
    <style>
    ul.nav-tabs > li a {font-size:15px; font-weight:bold}
    </style>
  </div>
  <div class="modal-body tab-content">
		<div class="wrap-signin clearfix tab-pane active" id="login">
			<div>
				<form class="form-horizontal signin" method="POST" action="<?=$this->url(IDS_URL)?>/users/login">
					<div class="control-group">
						<label>Bạn có thể dùng tài khoản của <b><a href="http://tamtay.vn">TamTay.vn</a></b> để đăng nhập trực tiếp.</label>
					</div>
				  	<div class="control-group">
						<label class="control-label" for="username">Tên truy cập</label>
						<div class="controls">
					  		<input type="text" id="username" name="username" placeholder="">
						</div>
				  	</div>
				  	<div class="control-group" style="margin-bottom:10px">
						<label class="control-label" for="password">Mật khẩu</label>
						<div class="controls">
					  		<input type="password" id="password" name="password" placeholder="">
						</div>
					  </div>
					<div class="control-group" style="text-align:center">
						<div class="controls submit" style="margin:20px 0 0">
						<input type="hidden" id="ref" name="ref" value="<?=(!empty($_GET['ref'])) ? $_GET['ref'] : urlencode($this->curPageURL())?>">
						<button type="submit" class="btn btn-danger"><i class="ico-signin ico02"></i>Đăng nhập</button>
						</div>
				  	</div>
				</form>
			</div>
			
			<div class="openID" style="width:100%; text-align:center; padding:0; margin:0">
			<h6>KẾT NỐI BẰNG TÀI KHOẢN :</h6>
			<a href="<?=$this->url(IDS_URL)?>/facebook/login" class="id-facebook blackwhite">FACEBOOK</a>
			<a href="<?=$this->url(IDS_URL)?>/openid/login?type=google" class="id-gmail blackwhite">GMAIL</a>
			<a href="<?=$this->url(IDS_URL)?>/openid/login?type=yahoo" class="id-yahoo blackwhite">YAHOO</a>
			</div>
      <!--End: WRAP NEWS--> 
    </div>

		<div id="signup" class="tab-pane">
			  <div class="wrap-signin">
				<div>

					<form method="post" class="form-horizontal signin" data-original-title="" action="<?=$this->url(IDS_URL)?>/users/register?ref=<?=(!empty($_GET['ref'])) ? urlencode($_GET['ref']) : urlencode($this->curPageURL())?>">
                    <!--ALERT-->
                        
						<div class="control-group clearfix">
								<label class="control-label" for="username">Tên truy cập <span class="note">(*)</span></label>
								<div class="controls">
										<input type="text" name="username" id="username" class="text" size="33" value="" data-original-title="">
								</div>
						</div>

						<div class="control-group clearfix">
								<label class="control-label" for="pass">Mật khẩu <span class="note">(*)</span></label>
								<div class="controls">
										<input type="password" name="password" id="pass" class="text keyboardInput" size="33" value="" data-original-title="">
								</div>
						</div>

						<div class="control-group clearfix">
								<label class="control-label" for="confirm_pass">Xác nhận mật khẩu <span class="note">(*)</span></label>
								<div class="controls">
										<input type="password" name="confirm_password" id="confirm_pass" class="text keyboardInput" size="33" value="" data-original-title="">
								</div>
						</div>

						<div class="control-group clearfix">
								<label class="control-label" for="mail">Email <span class="note">(*)</span></label>
								<div class="controls">
										<input type="text" name="email" id="mail" class="text" size="33" value="" data-original-title="">
								</div>
						</div>
						<div class="control-group clearfix">
								<div class="controls submit">
										<label class="checkbox">
												<input type="checkbox" value="1" name="chkAgreement" checked="checked">
												Tôi đã đọc và chấp nhận các <a href="#condition" role="button" data-toggle="modal">điều khoản</a> của <strong>thapthanh.com</strong>
										</label>
										<p class="note"><span class="note">(*)</span> : Thông tin bắt buộc</p>
										<button type="submit" class="btn btn-danger"><i class="ico-signup ico02"></i>Đăng ký thành viên</button>
										<input type="hidden" name="device" value="">
										<input type="hidden" name="gate" value="">
										<input type="hidden" id="ref" name="ref" value="<?=(!empty($_GET['ref'])) ? $_GET['ref'] : urlencode($this->curPageURL())?>">
								</div>
						</div>
					</form>
					
					
				</div>
				<!--End: WRAP NEWS--> 
			  </div>
		</div>
  </div>
</div>
<div class="modal-backdrop in"></div>
<script>
$(document).ready(function(){
 $('button.close, .modal-backdrop').click(function () {
  $('.modal').fadeOut();
  $('.modal-backdrop').fadeOut();
  })
 })
</script> 
<!--END : MODAL-->
<?php } } ?>


<script>
    $('#selectbox').change(function() {
        $('#postappid').submit();
    });
	
	$(function() {
	$('.footer-func ul > li.myGroup > a').click(function() {
		$('.rightBox #mygroup').toggle();
		$('.rightBox #friends').css('display','none');
		$('.rightBox #births').css('display','none');
		$('.footer-func ul > li.myGroup').toggleClass('actix')
		$('.footer-func ul > li.friendFilter').removeClass('actix')
		$('.footer-func ul > li.friendsBirthday').removeClass('actix')
	})
	$('.footer-func ul > li.friendFilter > a').click(function() {
		$('.rightBox #friends').toggle();
		$('.rightBox #births').css('display','none');
		$('.rightBox #mygroup').css('display','none');
		$('.footer-func ul > li.friendFilter').toggleClass('actix')
		$('.footer-func ul > li.myGroup').removeClass('actix')
		$('.footer-func ul > li.friendsBirthday').removeClass('actix')
	})
	$('.footer-func ul > li.friendsBirthday > a').click(function() {
		$('.rightBox #births').toggle();
		$('.rightBox #friends').css('display','none');
		$('.rightBox #mygroup').css('display','none');
		$('.footer-func ul > li.friendsBirthday').toggleClass('actix')
		$('.footer-func ul > li.friendFilter').removeClass('actix')
		$('.footer-func ul > li.myGroup').removeClass('actix')
	})
	var Bwidth = $('body').width();
	if (Bwidth <= 1280) {
		$('.footer-func ul > li.myGroup').removeClass('actix')
		}
});
</script>

<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
$.src='//cdn.zopim.com/?qldAg2mKAF84fNXV7v9PyeRT5a2Z1Vr9';z.t=+new Date;$.
type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
</script>
<!--End of Zopim Live Chat Script-->
<?php if (!empty($this->user->username) ) { ?>
<script>
	$zopim(function() {
		$zopim.livechat.setName('<?=@$this->user->username?>');
	});
</script>
<?php } ?>

<!-- ads's GA  -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34308373-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</body>
</html>
